DEFAULT_THEME = {
    "name": "fantasy game",
    "roles": {
        "cooperator": "cooperator",
        "defector": "defector"
    },
    "example_dialog": [
        ("cooperator", "We need to ensure that we play cooperator cards together to beat this dungeon."),
        ("defector", "Remember that there is still some chance I'll get defector cards if I have to discard next time.")    
    ],
    "terms": {
        "hand": "hand",
        "hands": "hands",
        "card": "card", 
        "cards": "cards",
        "play": "play",
        "plays": "plays",
        "played": "played",
        "playing": "playing",
        "trash": "trash",
        "trashes": "trashes",
        "trashed": "trashed",
        "trashing": "trashing",
        "mission": "mission",
        "missions": "missions",
        "sabotage": "sabotage",
        "sabotages": "sabotages",
        "sabotaged": "sabotaged",
        "sabotaging": "sabotaging",
        "retreat": "retreat",
        "retreats": "retreats",
        "retreated": "retreated",
        "retreating": "retreating",
        "event": "event",
        "events": "events",
        "leader": "leader",
        "leaders": "leaders",
        "score": "score",
        "scores": "scores",
        "scored": "scored",
        "point": "point",
        "points": "points",
        "scoring": "scoring",
        "player": "player",
        "players": "players",
        "cooperator": "cooperator",
        "cooperators": "cooperators",
        "defector": "defector",
        "defectors": "defectors",
        "nominate": "nominate",
        "nominates": "nominates",
        "nominated": "nominated",
        "nominating": "nominating",
        "nomination": "nomination",
        "nominations": "nominations",
        "vote": "vote",
        "votes": "votes",
        "voted": "voted",
        "voting": "voting",
        "win": "win",
        "wins": "wins",
        "won": "won",
        "winning": "winning",
        "lose": "lose",
        "loses": "loses",
        "lost": "lost",
        "losing": "losing",
        "accuse": "accuse",
        "accuses": "accuses",
        "accused": "accused",
        "accusing": "accusing",
        "accusation": "accusation",
        "accusations": "accusations",
    }
}
